// Builds js/items.js, the Reference tab's extended Equipment set, from the
// item catalogue the companion DM Screen project publishes.
//
// Why from there and not the Open5e API directly: DM Screen has already pulled
// these together from several documents, reconciled the field names, and split
// gear from magic items. Its file is public, so this stays reproducible.
//
// Run by hand:  node tools/build-items.js
const fs = require("fs");
const path = require("path");
const https = require("https");

const SOURCE = "https://dmscreen.github.io/data/items.json";
const RAW = path.join(__dirname, "raw", "dmscreen", "items.json");
const OUT = path.join(__dirname, "..", "js", "items.js");

// Open5e catalogues the Level Up line under two document keys that mean the
// same book line to a reader, so they share one chip here.
const SOURCE_NAMES = {
  "SRD 5.1": "SRD 5.1",
  "Level Up Advanced 5e": "Level Up A5E",
  "Level Up A5E SRD": "Level Up A5E",
  "Vault of Magic": "Vault of Magic",
  "Tome of Heroes": "Tome of Heroes",
  "Critical Role: Tal’Dorei Campaign Setting": "Tal'Dorei"
};

function get(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { "User-Agent": "charactergenerator/1.0" } }, res => {
      if (res.statusCode !== 200) return reject(new Error(`${res.statusCode} for ${url}`));
      const parts = [];
      res.on("data", d => parts.push(d));
      res.on("end", () => resolve(Buffer.concat(parts)));
    }).on("error", reject);
  });
}

// Straight quotes and no em dashes, to match the rest of the app's copy.
function tidy(s) {
  return String(s || "")
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/\s*[—]\s*/g, " - ")
    .replace(/\s+/g, " ")
    .trim();
}

(async () => {
  let raw;
  if (fs.existsSync(RAW)) {
    raw = JSON.parse(fs.readFileSync(RAW, "utf8"));
    console.log(`using cached ${path.relative(process.cwd(), RAW)} (delete it to re-pull)`);
  } else {
    console.log(`fetching ${SOURCE}`);
    raw = JSON.parse((await get(SOURCE)).toString("utf8"));
    fs.mkdirSync(path.dirname(RAW), { recursive: true });
    fs.writeFileSync(RAW, JSON.stringify(raw));
  }

  const unknown = new Set();
  const sources = [];
  const items = [];
  let noText = 0;

  for (const o of raw) {
    const src = SOURCE_NAMES[o.source];
    if (!src) { unknown.add(o.source); continue; }

    const desc = tidy(o.desc);
    const details = tidy(o.details);
    const cost = tidy(o.cost);
    const weight = tidy(o.weight);
    // A magic item with no text is just a name; gear at least says what it
    // costs and what it weighs, which is the whole point of looking it up.
    if (!desc && !details && !(cost || weight)) { noText++; continue; }

    let si = sources.indexOf(src);
    if (si < 0) si = sources.push(src) - 1;

    const r = { n: tidy(o.name), c: tidy(o.category), s: si };
    if (o.kind === "magic") r.m = 1;
    if (o.rarity) r.r = tidy(o.rarity);
    if (o.attunement) r.a = tidy(o.attunement);
    if (cost) r.p = cost;
    if (weight) r.w = weight;
    if (details) r.x = details;
    if (desc) r.d = desc;
    items.push(r);
  }

  if (unknown.size) console.log(`skipped unrecognised sources: ${[...unknown].join(", ")}`);
  console.log(`skipped ${noText} entries with no text and no price`);

  const banner =
    "// GENERATED by tools/build-items.js - do not hand-edit.\n" +
    "// Equipment and magic items for the Reference tab, compiled by the DM Screen\n" +
    "// project from the SRD 5.1, Level Up: Advanced 5th Edition, and open content\n" +
    "// released by Kobold Press and Green Ronin. See Settings for the attribution.\n" +
    "// Loaded on demand the first time the Reference tab is opened.\n";

  const js = banner +
    "const ITEM_SOURCES = " + JSON.stringify(sources) + ";\n" +
    "const EXTRA_ITEMS = " + JSON.stringify(items) + ";\n" +
    "if (typeof onItemsLoaded === \"function\") onItemsLoaded();\n";

  fs.writeFileSync(OUT, js);

  const bySource = {};
  items.forEach(i => { bySource[sources[i.s]] = (bySource[sources[i.s]] || 0) + 1; });
  console.log(`\n${path.relative(process.cwd(), OUT)}  ${items.length} items  ${(js.length / 1024 / 1024).toFixed(2)} MB`);
  console.log(`  magic ${items.filter(i => i.m).length}, gear ${items.filter(i => !i.m).length}`);
  Object.entries(bySource).sort((a, b) => b[1] - a[1]).forEach(([s, n]) => console.log(`  ${s.padEnd(16)} ${n}`));
})().catch(e => { console.error(e.message); process.exit(1); });
